server 
{
    listen 80;  
    
   
        alias /app/static/;  
        expires 1y;         
    }
    
   
    location /media/ {
        alias /app/media/;
        expires 1y;
    }
    
   
    location / {
        proxy_pass http://backend:8000; 
       
    }
